=== UO271572/SEW-XML/Ejercicio 1/Tarea 2/redsocial.dtd
<!ELEMENT persona (datos,(persona,persona,persona)?)>
<!ELEMENT datos (nacimiento,residencia,imagenes,videos,comentarios)>

<!ELEMENT nacimiento (fechaNacimiento,lugarNacimiento,coordenadasNacimiento)>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT lugarNacimiento (#PCDATA)>
<!ELEMENT coordenadasNacimiento (longitud,latitud,altitud)>

<!ELEMENT residencia (coordenadasResidencia)>
<!ELEMENT coordenadasResidencia (longitud,latitud,altitud)>

<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

<!ELEMENT imagenes (foto+)>
<!ELEMENT foto (#PCDATA)>

<!ELEMENT videos (video?,video?,video?)>
<!ELEMENT video (#PCDATA)>

<!ELEMENT comentarios (comentario+)>
<!ELEMENT comentario (#PCDATA)>

<!ATTLIST residencia lugarResidencia CDATA #REQUIRED>
<!ATTLIST persona nombre CDATA #REQUIRED>
<!ATTLIST persona apellidos CDATA #REQUIRED>

=== UO271572/SEW-XML/Ejercicio 1/Tarea 3/redsocial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persona SYSTEM "redsocial.dtd">

<persona nombre = "Fulgencio" apellidos="Estrada">
    <datos>
        <nacimiento>
            <fechaNacimiento>7-10-2000</fechaNacimiento>
            <lugarNacimiento>Colloto</lugarNacimiento>
            <coordenadasNacimiento>
                <longitud>-5.794783151573485</longitud>
                <latitud>43.3786951610564</latitud>
                <altitud>0</altitud>
            </coordenadasNacimiento>
        </nacimiento>
        <residencia lugarResidencia="Oviedo">
            <coordenadasResidencia>
                <longitud>-5.849154952690233</longitud>
                <latitud>43.36880577120749</latitud>
                <altitud>0</altitud>
            </coordenadasResidencia>
        </residencia>
        <!--Minimo 1 imagen-->
        <imagenes>
            <foto>imagen1.png</foto>
        </imagenes>
        <!--de 0 a 3 videos-->
        <videos>
            <video>video1.mp4</video>
            <video>video2.mp4</video>
            <video>video3.mp4</video>
        </videos>
        <!--Tiene comentarios o no tiene-->
        <comentarios>
            <comentario>Comentario 1</comentario>
            <comentario>Comentario 2</comentario>
            <comentario>Comentario 3</comentario>
            <comentario>Comentario 4</comentario>
        </comentarios>
    </datos>
    <!--Pueden enlazarse 3 personas-->
    <persona nombre = "Pablo" apellidos="Rubicon">
        <datos>
            <nacimiento>
                <fechaNacimiento>7-10-1996</fechaNacimiento>
                <lugarNacimiento>Leon</lugarNacimiento>
                <coordenadasNacimiento>
                    <longitud>-5.587750454882339</longitud>
                    <latitud>42.58378069349824</latitud>
                    <altitud>0</altitud>
                </coordenadasNacimiento>
            </nacimiento>
            <residencia lugarResidencia="Valladolid">
                <coordenadasResidencia>
                    <longitud>-4.741176777954699</longitud>
                    <latitud>41.643777379048075</latitud>
                    <altitud>0</altitud>
                </coordenadasResidencia>
            </residencia>
            <!--Minimo 1 imagen-->
            <imagenes>
                <foto>imagen1.png</foto>
                <foto>imagen2.png</foto>
                <foto>imagen3.png</foto>
            </imagenes>
            <!--de 0 a 3 videos-->
            <videos>
                <video>video3.mp4</video>
            </videos>
            <!--Tiene comentarios o no tiene-->
            <comentarios>
                <comentario>Comentario 4</comentario>
            </comentarios>
        </datos>
        <!--Pueden enlazarse 3 personas-->
        <persona nombre = "Risto" apellidos="Mejide">
            <datos>
                <nacimiento>
                    <fechaNacimiento>1-4-2001</fechaNacimiento>
                    <lugarNacimiento>Paris</lugarNacimiento>
                    <coordenadasNacimiento>
                        <longitud>2.259217945642413</longitud>
                        <latitud>48.81104412080502</latitud>
                        <altitud>0</altitud>
                    </coordenadasNacimiento>
                </nacimiento>
                <residencia lugarResidencia="Lyon">
                    <coordenadasResidencia>
                        <longitud>4.8758589359738105</longitud>
                        <latitud>45.74641168677539</latitud>
                        <altitud>0</altitud>
                    </coordenadasResidencia>
                </residencia>
                <!--Minimo 1 imagen-->
                <imagenes>
                    <foto>imagen3.png</foto>
                </imagenes>
                <!--de 0 a 3 videos-->
                <videos>
        
                </videos>
                <!--Tiene comentarios o no tiene-->
                <comentarios>
                    <comentario>Comentario 1</comentario>
                    <comentario>Comentario 2</comentario>
                    <comentario>Comentario 3</comentario>
                    <comentario>Comentario 4</comentario>
                </comentarios>
            </datos>
            <!--Pueden enlazarse 3 personas-->
        </persona>
        <persona nombre = "Charles" apellidos="Leclerc">
            <datos>
                <nacimiento>
                    <fechaNacimiento>20-6-2000</fechaNacimiento>
                    <lugarNacimiento>Monaco</lugarNacimiento>
                    <coordenadasNacimiento>
                        <longitud>7.035723445540587</longitud>
                        <latitud>43.60467082383504</latitud>
                        <altitud>0</altitud>
                    </coordenadasNacimiento>
                </nacimiento>
                <residencia lugarResidencia="Monaco">
                    <coordenadasResidencia>
                        <longitud>7.035723445540587</longitud>
                        <latitud>43.60467082383504</latitud>
                        <altitud>0</altitud>
                    </coordenadasResidencia>
                </residencia>
                <!--Minimo 1 imagen-->
                <imagenes>
                    <foto>imagen1.png</foto>
                    <foto>imagen2.png</foto>
                    <foto>imagen3.png</foto>
                </imagenes>
                <!--de 0 a 3 videos-->
                <videos>
        
                </videos>
                <!--Tiene comentarios o no tiene-->
                <comentarios>
                    <comentario>Comentario 3</comentario>
                    <comentario>Comentario 4</comentario>
                </comentarios>
            </datos>
            <!--Pueden enlazarse 3 personas-->
        </persona>
        <persona nombre = "Charles" apellidos="Puyol">
            <datos>
                <nacimiento>
                    <fechaNacimiento>7-10-2000</fechaNacimiento>
                    <lugarNacimiento>Barcelona</lugarNacimiento>
                    <coordenadasNacimiento>
                        <longitud>2.1249468262940967</longitud>
                        <latitud>41.40164699766722</latitud>
                        <altitud>0</altitud>
                    </coordenadasNacimiento>
                </nacimiento>
                <residencia lugarResidencia="Barcelona">
                    <coordenadasResidencia>
                        <longitud>2.1249468262940967</longitud>
                        <latitud>41.40164699766722</latitud>
                        <altitud>0</altitud>
                    </coordenadasResidencia>
                </residencia>
                <!--Minimo 1 imagen-->
                <imagenes>
                    <foto>imagen1.png</foto>
                    <foto>imagen3.png</foto>
                </imagenes>
                <!--de 0 a 3 videos-->
                <videos>
                    <video>video1.mp4</video>
                    <video>video2.mp4</video>
                    <video>video3.mp4</video>
                </videos>
                <!--Tiene comentarios o no tiene-->
                <comentarios>
                    <comentario>Comentario 1</comentario>
                    <comentario>Comentario 4</comentario>
                </comentarios>
            </datos>
            <!--Pueden enlazarse 3 personas-->
        </persona>
    </persona>
    <persona nombre = "Marta" apellidos="Ortin">
        <datos>
            <nacimiento>
                <fechaNacimiento>6-6-1998</fechaNacimiento>
                <lugarNacimiento>Salamanca</lugarNacimiento>
                <coordenadasNacimiento>
                    <longitud>-5.673896457382607</longitud>
                    <latitud>40.947276319501576</latitud>
                    <altitud>0</altitud>
                </coordenadasNacimiento>
            </nacimiento>
            <residencia lugarResidencia="Sevilla">
                <coordenadasResidencia>
                    <longitud>-5.965679477848744</longitud>
                    <latitud>37.37452863427277</latitud>
                    <altitud>0</altitud>
                </coordenadasResidencia>
            </residencia>
            <!--Minimo 1 imagen-->
            <imagenes>
                <foto>imagen3.png</foto>
            </imagenes>
            <!--de 0 a 3 videos-->
            <videos>
                <video>video1.mp4</video>
                <video>video3.mp4</video>
            </videos>
            <!--Tiene comentarios o no tiene-->
            <comentarios>
                <comentario>Comentario 1</comentario>
                <comentario>Comentario 2</comentario>
                <comentario>Comentario 3</comentario>
                <comentario>Comentario 4</comentario>
            </comentarios>
        </datos>
        <!--Pueden enlazarse 3 personas-->
        <persona nombre = "Rafa" apellidos="Mora">
            <datos>
                <nacimiento>
                    <fechaNacimiento>7-10-2005</fechaNacimiento>
                    <lugarNacimiento>Leon</lugarNacimiento>
                <coordenadasNacimiento>
                    <longitud>-5.587750454882339</longitud>
                    <latitud>42.58378069349824</latitud>
                    <altitud>0</altitud>
                </coordenadasNacimiento>
                </nacimiento>
                <residencia lugarResidencia="Sevilla">
                    <coordenadasResidencia>
                        <longitud>-5.965679477848744</longitud>
                        <latitud>37.37452863427277</latitud>
                        <altitud>0</altitud>
                    </coordenadasResidencia>
                </residencia>
                <!--Minimo 1 imagen-->
